### ISSUE TITLE
MXEXmlArray not defined.

### ISSUE THREAD

**Issue by maxpaynebupt** [soranoba/MantleXMLExtension#1]
trying to use MXEXmlAttribute, but these classes or macro or function of defined where can I find the definition?
    return @{ @"status" : MXEXmlAttribute(@"", @"status"),
              @"userCount" : @"summary.count",
              @"users" : MXEXmlArray(@"", MXEXmlChildNode(@"user")) };

**Comment by maxpaynebupt** [comment]
forgot to import some headers.

**Comment by soranoba** [comment]
Please write `#import <MantleXMLExtension/MantleXMLExtension.h>` or `@import MantleXMLExtension;`

If you want more help, please tell me the package manager you are using and the import you are writing.
